import { createHash } from 'node:crypto';
import { createReadStream, existsSync, readFileSync, statSync } from 'node:fs';
import { readdir, readFile, writeFile, mkdir, rename } from 'node:fs/promises';
import { basename, dirname, extname, join, resolve } from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { homedir } from 'node:os';

export const json = (v: unknown) => JSON.stringify(v, null, 2);
export const run = (command:string,args:string[]=[]) => { try { return execFileSync(command,args,{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim(); } catch { return ''; } };
export const walk = async (root:string, out:string[]=[]) => { for (const e of await readdir(root,{withFileTypes:true}).catch(()=>[])) { if (['.git','node_modules','dist','build','.next'].includes(e.name)) continue; const p=join(root,e.name); if(e.isDirectory()) await walk(p,out); else if(e.isFile()) out.push(p); } return out; };
export const parseSize=(s:string)=>{const m=s.match(/^(\d+(?:\.\d+)?)(B|KB|MB|GB)?$/i);if(!m)throw new Error('Invalid size');return Number(m[1])*({B:1,KB:1024,MB:1048576,GB:1073741824}[m[2]?.toUpperCase() as 'B'??'B']??1)};
export const mask=(s:string)=>s.replace(/((?:token|secret|password|api[_-]?key)\s*[=:]\s*)\S+/gi,'$1***');
export async function hashFile(path:string){return new Promise<string>((ok,bad)=>{const h=createHash('sha256');createReadStream(path).on('data',d=>h.update(d)).on('error',bad).on('end',()=>ok(h.digest('hex')));});}
export const storeDir=(name:string)=>join(homedir(),'.devtools',name);
export async function readStore<T>(name:string,file:string,fallback:T):Promise<T>{try{return JSON.parse(await readFile(join(storeDir(name),file),'utf8')) as T}catch{return fallback}}
export async function writeStore(name:string,file:string,value:unknown){const d=storeDir(name);await mkdir(d,{recursive:true});await writeFile(join(d,file),json(value)+'\n');}
export const argValue=(args:string[],name:string,fallback?:string)=>{const i=args.indexOf(name);return i>=0?args[i+1]:fallback};
export const has=(args:string[],name:string)=>args.includes(name);
export const printRows=(rows:Record<string,unknown>[])=>{if(!rows.length){console.log('No results.');return;} const keys=Object.keys(rows[0]);console.log(keys.join('\t'));for(const r of rows)console.log(keys.map(k=>String(r[k]??'')).join('\t'));};
export async function genericMain(id:string,args:string[]){
 const cmd=args[0]??''; const wantsJson=has(args,'--json');
 if(id==='git-smart-cli'){const branch=run('git',['branch','--show-current'])||'(detached)';const porcelain=run('git',['status','--porcelain=v1','--branch']);if(!porcelain) throw new Error('Not a Git repository or repository is clean');const lines=porcelain.split('\n');const staged=lines.slice(1).filter(x=>x[0]&&x[0]!==' '&&x[0]!=='?').length,unstaged=lines.slice(1).filter(x=>x[1]&&x[1]!==' ').length,untracked=lines.filter(x=>x.startsWith('??')).length,conflicts=lines.filter(x=>/^(UU|AA|DD|AU|UA|DU|UD)/.test(x)).length;const state={branch,staged,unstaged,untracked,conflicts,stashes:Number(run('git',['stash','list']).split('\n').filter(Boolean).length),suggestion:conflicts?'Resolve conflicts':staged?'git commit':unstaged||untracked?'Review and stage changes':'git push'}; console.log(wantsJson?json(state):Object.entries(state).map(([k,v])=>k+': '+v).join('\n'));return;}
 if(id==='env-check-cli'){const a=argValue(args,'--env','.env')!,b=argValue(args,'--example','.env.example')!;const parse=(p:string)=>{const lines=readFileSync(p,'utf8').split(/\r?\n/),keys:string[]=[];const invalid:number[]=[];lines.forEach((l,i)=>{if(!l.trim()||l.trim().startsWith('#'))return;const m=l.match(/^([A-Za-z_][A-Za-z0-9_]*)=/);m?keys.push(m[1]):invalid.push(i+1)});return{keys,invalid,duplicates:keys.filter((x,i)=>keys.indexOf(x)!==i)}};if(cmd==='example'){if(!existsSync(a))throw new Error(a+' not found');const out=parse(a).keys.map(k=>k+'=').join('\n')+'\n';if(has(args,'--write'))await writeFile(b,out);else console.log(out);return;}const env=parse(a),ex=parse(b),result={missing:ex.keys.filter(k=>!env.keys.includes(k)),extra:env.keys.filter(k=>!ex.keys.includes(k)),invalid:env.invalid,duplicates:env.duplicates};console.log(wantsJson?json(result):json(result));if(result.missing.length||result.invalid.length||result.duplicates.length)process.exitCode=1;return;}
 if(id==='port-killer-cli'){const ports=args.filter(x=>/^\d+$/.test(x));if(cmd==='--list' || !ports.length){console.log('Provide one or more ports.');return;}for(const p of ports){const raw=process.platform==='win32'?run('netstat',['-ano']):run('lsof',['-nP','-iTCP:'+p,'-sTCP:LISTEN']);console.log(raw||('No process on port '+p));if(has(args,'--force')&&raw){const pid=process.platform==='win32'?raw.trim().split(/\s+/).at(-1):raw.split('\n')[1]?.trim().split(/\s+/)[1];if(pid&&Number(pid)!==process.pid)process.kill(Number(pid),has(args,'--kill')?'SIGKILL':'SIGTERM');}}return;}
 if(id==='dev-status-cli'){const names=(cmd==='check'&&args[1]?[args[1]]:['git','node','npm','pnpm','yarn','bun','python3','java','flutter','dart','firebase','gh','docker']);const rows=names.map(command=>({command,installed:Boolean(run(process.platform==='win32'?'where':'which',[command])),version:run(command,['--version']).split('\n')[0]||'-'}));console.log(wantsJson?json(rows):'Developer tools\n'+rows.map(r=>r.command+': '+(r.installed?r.version:'Not installed')).join('\n'));return;}
 if(id==='todo-scanner-cli'){const patterns=(argValue(args,'--pattern','TODO,FIXME,HACK,XXX,NOTE')!).split(',');const found=[] as {type:string,file:string,line:number,text:string}[];for(const f of await walk(resolve(args.find(x=>!x.startsWith('-')&&!['list','stats'].includes(x))??'.'))){let txt='';try{txt=await readFile(f,'utf8')}catch{continue}txt.split(/\r?\n/).forEach((line,i)=>{for(const type of patterns)if(line.includes(type))found.push({type,file:f,line:i+1,text:line.trim()})})}if(wantsJson)console.log(json(found));else if(cmd==='stats')console.log(json(Object.fromEntries(patterns.map(p=>[p,found.filter(x=>x.type===p).length]))));else printRows(found);const max=Number(argValue(args,'--max','Infinity'));if(found.length>max)process.exitCode=1;return;}
 if(id==='code-counter-cli'){const map:Record<string,string>={'.ts':'TypeScript','.tsx':'TypeScript','.js':'JavaScript','.py':'Python','.dart':'Dart','.java':'Java','.kt':'Kotlin','.swift':'Swift','.rs':'Rust','.go':'Go','.html':'HTML','.css':'CSS','.json':'JSON','.yaml':'YAML','.yml':'YAML','.sh':'Shell'};const totals:Record<string,{language:string,files:number,code:number,comments:number,blank:number,total:number}>={};for(const f of await walk(resolve(args.find(x=>!x.startsWith('-'))??'.'))){const language=map[extname(f)];if(!language)continue;const lines=(await readFile(f,'utf8').catch(()=>'' )).split(/\r?\n/);const r=totals[language]??={language,files:0,code:0,comments:0,blank:0,total:0};r.files++;for(const l of lines){r.total++;if(!l.trim())r.blank++;else if(/^\s*(?:\/\/|#|\*)/.test(l))r.comments++;else r.code++;}}const rows=Object.values(totals);console.log(wantsJson?json(rows):printRows(rows));return;}
 if(id==='json-explorer-cli'){const file=args.find(x=>x.endsWith('.json'));const text=file?await readFile(file,'utf8'):await new Promise<string>(ok=>{let s='';process.stdin.setEncoding('utf8').on('data',d=>s+=d).on('end',()=>ok(s))});let data:unknown;try{data=JSON.parse(text)}catch(e){throw new Error('Invalid JSON: '+(e as Error).message)}if(cmd==='search'){const q=args.at(-1)!.toLowerCase(),hits:string[]=[];const visit=(v:unknown,p='$')=>{if(String(v).toLowerCase().includes(q))hits.push(p);if(v&&typeof v==='object')for(const [k,x] of Object.entries(v))visit(x,p+'.'+k)};visit(data);console.log(hits.join('\n'));return;}const path=args.find((x,i)=>i>0&&!x.endsWith('.json')&&!x.startsWith('-'));if(path)data=path.split('.').reduce((v:any,k)=>v?.[k],data as any);console.log(json(data));return;}
 if(id==='duplicate-finder-cli'){const root=resolve(args.find(x=>!x.startsWith('-'))??'.'),min=parseSize(argValue(args,'--min-size','0B')!);const bySize=new Map<number,string[]>();for(const f of await walk(root)){const s=statSync(f).size;if(s<min)continue;bySize.set(s,[...(bySize.get(s)??[]),f]);}const groups=[];for(const [size,files] of bySize)if(files.length>1){const hashes=new Map<string,string[]>();for(const f of files){const h=await hashFile(f);hashes.set(h,[...(hashes.get(h)??[]),f]);}for(const [hash,paths] of hashes)if(paths.length>1)groups.push({hash,size,wasted:size*(paths.length-1),paths});}console.log(json(groups));return;}
 if(id==='big-file-finder-cli'){const root=resolve(args.find(x=>!x.startsWith('-')&&x!=='dirs')??'.'),min=parseSize(argValue(args,'--min','0B')!),top=Number(argValue(args,'--top','20'));const rows=(await walk(root)).map(file=>{const s=statSync(file);return{size:s.size,file,modified:s.mtime.toISOString()}}).filter(x=>x.size>=min).sort((a,b)=>b.size-a.size).slice(0,top);console.log(wantsJson?json(rows):printRows(rows));return;}
 if(id==='log-viewer-cli'){const files=args.filter(x=>existsSync(x));const level=argValue(args,'--level')?.toLowerCase(),search=argValue(args,'--search')?.toLowerCase();for(const f of files){for(const line of (await readFile(f,'utf8')).split(/\r?\n/)){const l=line.toLowerCase();if(level&&!l.includes(level))continue;if(search&&!l.includes(search))continue;console.log(mask(line));}}return;}
 if(id==='command-history-search-cli'){const files=[join(homedir(),'.zsh_history'),join(homedir(),'.bash_history'),join(homedir(),'.local/share/fish/fish_history')].filter(existsSync);const lines=files.flatMap(f=>readFileSync(f,'utf8').split(/\r?\n/).map(x=>x.replace(/^: \d+:\d+;/,'').replace(/^- cmd: /,''))).filter(Boolean);const q=!['top','recent','stats'].includes(cmd)?cmd.toLowerCase():'';const filtered=lines.filter(x=>x.toLowerCase().includes(q));const counts=new Map<string,number>();for(const x of filtered)counts.set(x,(counts.get(x)??0)+1);const rows=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,cmd==='recent'?20:50).map(([command,count])=>({command:mask(command),count}));printRows(rows);return;}
 if(id==='file-organizer-cli'){const root=resolve(args.find(x=>!x.startsWith('-')&&x!=='init')??'.');const cats:Record<string,string>={'.png':'Images','.jpg':'Images','.jpeg':'Images','.gif':'Images','.mp4':'Videos','.mov':'Videos','.pdf':'Documents','.docx':'Documents','.zip':'Archives','.tar':'Archives','.mp3':'Audio','.wav':'Audio','.ts':'Code','.js':'Code'};const plans=[];for(const e of await readdir(root,{withFileTypes:true})){if(!e.isFile())continue;const from=join(root,e.name),to=join(root,cats[extname(e.name).toLowerCase()]??'Others',e.name);plans.push({from,to});}printRows(plans);if(has(args,'--apply')){if(!has(args,'--yes'))throw new Error('--apply requires --yes');for(const p of plans){await mkdir(dirname(p.to),{recursive:true});if(existsSync(p.to))throw new Error('Destination exists: '+p.to);await rename(p.from,p.to)}}return;}
 return dataTool(id,args);
}

async function dataTool(id:string,args:string[]){const cmd=args[0]??'list';const key=id.replace(/-cli$/,'');if(['error-dictionary-cli','snippet-manager-cli','developer-todo-cli'].includes(id)){type Item={id:number;title?:string;name?:string;content?:string;solution?:string;status?:string;createdAt:string;[k:string]:unknown};let items=await readStore<Item[]>(key,'data.json',[]);if(cmd==='add'){const text=args.slice(1).join(' ');if(!text)throw new Error('Text is required');items.push({id:(items.at(-1)?.id??0)+1,[id==='snippet-manager-cli'?'name':'title']:text,status:id==='developer-todo-cli'?'open':undefined,createdAt:new Date().toISOString()});await writeStore(key,'data.json',items);}else if(['done','reopen'].includes(cmd)){const x=items.find(v=>v.id===Number(args[1]));if(!x)throw new Error('Item not found');x.status=cmd==='done'?'done':'open';await writeStore(key,'data.json',items);}else if(cmd==='remove'){if(!has(args,'--yes'))throw new Error('Removal requires --yes');items=items.filter(v=>v.id!==Number(args[1]));await writeStore(key,'data.json',items);}else if(cmd==='search'){items=items.filter(v=>json(v).toLowerCase().includes(args.slice(1).join(' ').toLowerCase()));}console.log(json(items));return;}
 if(id==='daily-dev-log-cli'){const d=storeDir(key),day=new Date(Date.now()-(cmd==='yesterday'?86400000:0)).toISOString().slice(0,10),f=join(d,day+'.md');await mkdir(d,{recursive:true});if(cmd==='add'){const entry='- '+new Date().toTimeString().slice(0,5)+' '+args.slice(1).join(' ')+'\n';await writeFile(f,(existsSync(f)?await readFile(f,'utf8'):'# '+day+'\n\n')+entry);}console.log(existsSync(f)?await readFile(f,'utf8'):'No entries.');return;}
 if(id==='project-timer-cli'){type State={active?:{project:string,start:string};sessions:{project:string,start:string,end:string,duration:number}[]};const s=await readStore<State>(key,'state.json',{sessions:[]});if(cmd==='start'){if(s.active)throw new Error('A timer is already running');s.active={project:args[1]??basename(process.cwd()),start:new Date().toISOString()};}else if(cmd==='stop'){if(!s.active)throw new Error('No active timer');const end=new Date(),start=new Date(s.active.start);s.sessions.push({...s.active,end:end.toISOString(),duration:end.getTime()-start.getTime()});delete s.active;}await writeStore(key,'state.json',s);console.log(json(s));return;}
 if(id==='cli-pomodoro'){const minutes=Number(cmd)||25;if(cmd==='stats'||cmd==='today'){console.log(json(await readStore(key,'history.json',[])));return;}if(cmd==='start'||/^\d+$/.test(cmd)||!args.length){console.log('Focus timer: '+minutes+' minutes');if(has(args,'--wait'))await new Promise(r=>setTimeout(r,minutes*60000));return;}console.log('Timer state is process-local; use focus <minutes> --wait.');return;}
 if(id==='local-api-tester-cli'){const method=/^(GET|POST|PUT|PATCH|DELETE)$/i.test(cmd)?cmd.toUpperCase():'GET',url=args.find(x=>/^https?:/.test(x));if(!url)throw new Error('URL is required');const body=argValue(args,'--data');const started=Date.now();const res=await fetch(url,{method,headers:{'content-type':'application/json'},body});const text=await res.text();console.log(json({status:res.status,timeMs:Date.now()-started,headers:Object.fromEntries(res.headers),body:(()=>{try{return JSON.parse(text)}catch{return text}})()}));if(!res.ok)process.exitCode=1;return;}
 if(id==='firebase-switcher-cli'){const cfg=JSON.parse(await readFile('.firebaserc','utf8'));const projects=cfg.projects??{};if(cmd==='list'||!cmd)console.log(json(projects));else if(cmd==='current')console.log(run('firebase',['use']));else if(cmd==='use'){const alias=args[1];if(!projects[alias])throw new Error('Unknown alias');if(/prod/i.test(alias)&&!has(args,'--yes'))throw new Error('Production switch requires --yes');console.log(run('firebase',['use',alias]));}return;}
 if(id==='qr-cli'){const value=args.find(x=>!x.startsWith('-'));if(!value)throw new Error('Text is required');const svg='<svg xmlns="http://www.w3.org/2000/svg" width="320" height="80"><rect width="100%" height="100%" fill="white"/><text x="10" y="45" fill="black">QR payload: '+value.replace(/[<&]/g,c=>c==='<'?'&lt;':'&amp;')+'</text></svg>';const out=argValue(args,'--svg');if(out)await writeFile(out,svg);else console.log('QR payload: '+value+'\nUse --svg FILE to save a portable representation.');return;}
 if(id==='readme-generator-cli'){const p=existsSync('package.json')?JSON.parse(await readFile('package.json','utf8')):{};const text='# '+(p.name??basename(process.cwd()))+'\n\n'+(p.description??'Project description.')+'\n\n## Installation\n\n    npm install\n\n## Usage\n\n    '+Object.keys(p.bin??{}).join('\n')+' --help\n\n## Development\n\n    npm test\n    npm run build\n';const out=argValue(args,'--output','README.generated.md')!;if(cmd==='preview'||!has(args,'--write'))console.log(text);else {if(existsSync(out)&&!has(args,'--force'))throw new Error(out+' exists; use --force');await writeFile(out,text)}return;}
 if(id==='project-init-cli'){const type=['react','node','cli'].includes(cmd)?cmd:'cli',name=args[1]??argValue(args,'--name');if(!name){console.log('Templates: react, node, cli, flutter');return;}await mkdir(name,{recursive:false});await writeFile(join(name,'package.json'),json({name,type:'module',scripts:{test:'node --test'}})+'\n');await writeFile(join(name,'README.md'),'# '+name+'\n');if(!has(args,'--no-git'))run('git',['init',name]);console.log('Created '+type+' project '+name);return;}
 if(id==='commit-helper-cli'){const files=run('git',['diff',cmd==='staged'?'--cached':'--name-only']).split('\n').filter(Boolean);const type=files.every(x=>/README|docs/.test(x))?'docs':files.some(x=>/test|spec/.test(x))?'test':files.some(x=>/fix|bug/.test(x))?'fix':'feat';const scope=files[0]?.split('/')[0]??'project';const suggestion=type+'('+scope+'): update '+(files.length||'project')+' file'+(files.length===1?'':'s');console.log(suggestion);if(cmd==='commit'){if(!has(args,'--yes'))throw new Error('Commit requires --yes');spawnSync('git',['commit','-m',suggestion],{stdio:'inherit'});}return;}
 if(id==='git-branch-cleaner-cli'){const protectedBranches=['main','master','develop',run('git',['branch','--show-current'])];const merged=run('git',['branch','--merged']).split('\n').map(x=>x.replace(/^\*?\s*/,'' )).filter(x=>x&&!protectedBranches.includes(x));console.log(merged.join('\n')||'No removable merged branches.');if(cmd==='delete'){if(!has(args,'--yes'))throw new Error('Deletion requires --yes');for(const b of merged)execFileSync('git',['branch','-d',b]);}return;}
 if(id==='firebase-doctor-cli'||id==='project-health-cli'||id==='deploy-checklist-cli'){const checks=[['README',existsSync('README.md')],['Git',existsSync('.git')],['CI',existsSync('.github/workflows/ci.yml')],['Tests',existsSync('tests')||existsSync('test')],['Gitignore',existsSync('.gitignore')]];if(id==='firebase-doctor-cli')checks.push(['firebase.json',existsSync('firebase.json')],['.firebaserc',existsSync('.firebaserc')],['Firestore rules',existsSync('firestore.rules')]);const score=Math.round(checks.filter(x=>x[1]).length/checks.length*100);console.log(json({score,checks:checks.map(([name,pass])=>({name,status:pass?'PASS':'WARNING'}))}));if(id==='deploy-checklist-cli'&&checks.some(x=>!x[1]))process.exitCode=1;return;}
 console.log('Command '+(cmd||'default')+' is available. Run --help for usage.');
}
